import = ["~/.config/alacritty/alacritty.local.toml",]

[window]
# padding = {x = 8, y = 4 }
dimensions = {columns = 150,lines = 40}
opacity = 0.90
dynamic_title = true
[font]
size = 11
normal = {family = "UDEV Gothic 35NFLG", style = "Regular" }
bold = {family = "UDEV Gothic 35NFLG", style = "Bold" }
italic = {family = "UDEV Gothic 35NFLG", style = "Italic" }
bold_italic = {family = "UDEV Gothic 35NFLG", style = "BoldItalic" }

[mouse]
hide_when_typing = true